sudo: required

services:
  - docker

osx_image: xcode9.3

matrix:
  include:
    - os: osx
      env: TEST_SH=mac_test.sh
    - os: linux
      # All linux tests are run through docker containers.
      env: TEST_SH=ubuntu_test.sh


script: "tests/scripts/${TEST_SH}"
